"""Build the skeleton's game atlas from the full set: one PNG, a JSON manifest, a C++ include.

The game set is idle, walk, attack, flinch (death is an engine effect, so there is none here), each at
all eight facings. The atlas is a grid: one row per (state, facing), one column per frame, 48x48 cells.

    row = state_index * 8 + facing_index          (facing_index = yaw / 45; 0 = facing the camera)
    col = frame within the state

Frame timing is per frame (the harness's `hold` x 1/fps), written as seconds, so the actor can drive the
frames itself. A one-shot state (attack, flinch) has to start at frame 0 when triggered, which the
material's own time-stepping cannot do; it steps frames only when it is given `Frames > 1, Fps > 0`.

    python examples/skeleton_warrior/make_game_atlas.py [--png OUT.png] [--json OUT.json] [--inl OUT.inl]

State mapping from the full set: idle -> idle, walk -> walk, attack_a -> attack, damage -> flinch.
"""
import argparse
import json
from pathlib import Path

import numpy as np
from PIL import Image

HERE = Path(__file__).parent
ap = argparse.ArgumentParser()
ap.add_argument("--png", default=str(HERE / "out/T_SprAtlas_Skeleton.png"))
ap.add_argument("--json", default=str(HERE / "out/T_SprAtlas_Skeleton.json"))
ap.add_argument("--inl", default=str(HERE / "out/SkeletonSpriteSet.inl"))
args = ap.parse_args()

CELL = 48
GAME_STATES = [("idle", "idle"), ("walk", "walk"), ("attack", "attack_a"), ("flinch", "damage")]

man = json.loads((HERE / "fullset_manifest.json").read_text(encoding="utf-8"))
ent = {(e["state"], e["facing"]): e for e in man["entries"]}
strip = np.array(Image.open(HERE / "out/fullset_strip.png").convert("RGBA"))
facings = man["facings"]
cols = max(ent[(src, 0)]["count"] for _, src in GAME_STATES)
rows = len(GAME_STATES) * len(facings)
atlas = np.zeros((rows * CELL, cols * CELL, 4), dtype=np.uint8)

states_out = []
for si, (name, src) in enumerate(GAME_STATES):
    e0 = ent[(src, 0)]
    durs = [round(h / e0["fps"], 4) for h in e0["holds"]]
    for fi, yaw in enumerate(facings):
        e = ent[(src, yaw)]
        assert e["count"] == e0["count"], (src, yaw)
        for k in range(e["count"]):
            cell = strip[:, (e["first"] + k) * CELL:(e["first"] + k + 1) * CELL]
            cell = cell[:, ::-1]        # M_Sprite's billboard right vector is the viewer's left, so it draws every cell mirrored; pre-mirror
            r = si * len(facings) + fi
            atlas[r * CELL:(r + 1) * CELL, k * CELL:(k + 1) * CELL] = cell
    states_out.append({"name": name, "source_state": src, "frames": e0["count"], "durations": durs,
                       "loop": bool(e0["loop"]), "commit_frame": e0.get("commit_frame"),
                       "row_base": si * len(facings)})

a = atlas[:, :, 3]
atlas[:, :, 3] = np.where(a > 127, 255, 0)              # binary alpha, as the material's alpha clip expects
atlas[atlas[:, :, 3] == 0, :3] = 0
Path(args.png).parent.mkdir(parents=True, exist_ok=True)
Image.fromarray(atlas, "RGBA").save(args.png)

manifest = {"name": "skeleton_warrior", "atlas": Path(args.png).name, "cell": [CELL, CELL],
            "size": [cols * CELL, rows * CELL], "columns": cols, "facings": facings,
            "row_formula": "row = row_base + facing_index; col = frame", "states": states_out,
            "pivot": "bottom centre; feet on row 46 of 48", "texel_uu": 4.5}
Path(args.json).write_text(json.dumps(manifest, indent=1), encoding="utf-8")

lines = ["// Generated by pixelanim examples/skeleton_warrior/make_game_atlas.py. Do not edit.",
         "// Skeleton game atlas: one row per (state, facing), one column per frame, 48x48 cells.",
         "constexpr int32 SkelCell = %d, SkelColumns = %d, SkelAtlasW = %d, SkelAtlasH = %d;" % (CELL, cols, cols * CELL, rows * CELL),
         "constexpr int32 SkelFacings = %d;" % len(facings), "",
         "struct FSkelState { const TCHAR* Name; int32 RowBase; int32 Frames; bool bLoop; int32 CommitFrame; float Durations[%d]; };" % cols,
         "constexpr FSkelState SkelStates[] = {"]
for s in states_out:
    d = s["durations"] + [0.0] * (cols - len(s["durations"]))
    lines.append('\t{TEXT("%s"), %d, %d, %s, %d, {%s}},' % (
        s["name"], s["row_base"], s["frames"], "true" if s["loop"] else "false",
        -1 if s["commit_frame"] is None else s["commit_frame"], ", ".join("%.4ff" % x for x in d)))
lines += ["};", "constexpr int32 SkelNumStates = %d;" % len(states_out), ""]
lines += ["enum class ESkelState : uint8 { %s };" % ", ".join(n.capitalize() for n, _ in GAME_STATES)]
Path(args.inl).write_text("\n".join(lines) + "\n", encoding="utf-8")
print("atlas %dx%d, %d rows x %d columns; %d states x %d facings" % (cols * CELL, rows * CELL, rows, cols, len(states_out), len(facings)))
for s in states_out:
    print("  %-7s %d frames, %s, %.2fs, commit %s" % (s["name"], s["frames"], "loop" if s["loop"] else "one-shot",
                                                     sum(s["durations"]), s["commit_frame"]))
